### ISSUE TITLE
Monero GUI transaction was sent, but not received?

### ISSUE THREAD

**Issue by bigpun87** [monero-project/monero-gui#1350]
Hi - I sent 1 monero to my Binance account, and it is showing as "sent" on my GUI if I "prove/check" the transaction, but on moneroblocks.info I cannot find the transaction at all. Binance is claiming they never received it either and it's been almost 2 days. My Monero GUI account was also reduced for 1 Monero, which implies it was sent? 

If it helps, I sent the transaction on an older version of the Monero GUI (version 11) and then upgraded to version 12 after to hope it would help, but it has not.

Tx ID: | 9f81ecaa5034180f601a469c0b7ef70ad270b1a7b57b6364aee01ce3d25434ef

Thanks

**Comment by dEBRUYNE-1** [comment]
See my post below:

>If your transaction does not show up on a blockexplorer like, for instance, [XMRchain](https://xmrchain.net) or [MoneroBlocks](https://moneroblocks.info), you, most likely, performed it on the wrong (alternative) chain. Therefore, you should be able to resolve your issue with this guide:

>https://monero.stackexchange.com/questions/7993/i-forgot-to-upgrade-from-cli-or-gui-v0-11-to-cli-or-gui-v0-12-and-created-pe

>Please note (from the [linked guide](https://monero.stackexchange.com/questions/7989/i-forgot-to-upgrade-from-cli-or-gui-v0-11-to-cli-or-gui-v0-12-and-as-a-result)):

>>As a general rule of thumb, for each day you synced after the fork height (1546000 or April 6) you have to pop 800 blocks. Thus, let's say you synced 10 days on the wrong (alternative) chain, you should use --pop-blocks 8000

>Since we're 17 days after the scheduled network upgrade, you ought to use `--pop-blocks 13600`

>P.S. I reckon aforementioned guide might be a bit convoluted. Therefore, if you need any assistance, feel free to shoot me a PM. 

>P.P.S. Your Monero should be back in your wallet after applying aforementioned guides.

**Comment by bigpun87** [comment]
unfortunately none of the above work - I re-synced the blockchain with the instructions provided to no avail and also upgrade to v0.12. I then ran the went "flush_txpool" but the transaction did not show as "failed". I then changed the wallet directory but that did not help.. Anyway to just wipe this clean and start from scratch? Feel exhausted from this

**Comment by bigpun87** [comment]
also, I would PM you, but no idea how to!

**Comment by dEBRUYNE-1** [comment]
@bigpun87 - You can PM me on reddit -> https://www.reddit.com/user/dEBRUYNE_1/

**Comment by victorgp** [comment]
Same happened to me, PM sent in reddit

**Comment by victorgp** [comment]
@bigpun87 @dEBRUYNE-1 i've managed to fix the problem by using a remote node, something that i wanted to avoid but it was my last resort, by using a local node i didn't manage to fix the problem, and i followed all the steps in that link.

You can get remote nodes from here https://moneroworld.com/

At least i have my coins again...

**Comment by VuyaniBottle** [comment]
Thanks to the guys who created the Monero Gui wallet. It is the shittiest wallet created ever.

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by jetflyer888** [comment]
@dEBRUYNE-1 thanks for all of the information, I tried https://www.reddit.com/r/Monero/comments/8vkx2g/gui_v01220_released/ but in my GUI transaction history I see the transaction (Monero GUI to Binance transaction) but haven't received funds in Binance. After upgrading to v01220 I still see transaction in history with funds not reinstated.

If you can offer any help that would be greatly appreciated as I'm stuck as to what to try next. Thanks

**Comment by jetflyer888** [comment]
@dEBRUYNE-1 all resolved now by installing v012.3.0 - thanks all for previous posts.

**Comment by alwaysru** [comment]
Thank you for this note @dEBRUYNE-1 - helped me recover 2 XMR! Appreciate you!
