### ISSUE TITLE
50 character password works in cli wallet but not in gui

### ISSUE THREAD

**Issue by tikwanleap** [monero-project/monero-gui#653]
I have a 50 character password that works in cli wallet but not in gui.

I tested in the latest versions of both cli and gui (0.10.3.1) on Windows 10 64-bit.

**Comment by medusadigital** [comment]
sounds like a possible bug. needs investigation

+bug

**Comment by dEBRUYNE-1** [comment]
Does it contain a space?

**Comment by tikwanleap** [comment]
It does not. But it does contain accented characters (non-ASCII).

**Comment by dEBRUYNE-1** [comment]
Does it contain parentheses as well?

**Comment by tikwanleap** [comment]
Yes it contains parentheses.

**Comment by skftn** [comment]
Related to #199 #758 #820 and eventually https://github.com/monero-project/monero/issues/1390

**Comment by medusadigital** [comment]
will be directly fixed in wallet2 API: https://github.com/monero-project/monero/issues/1390

closing here. 

thanks for report

**Comment by medusadigital** [comment]
+duplicate

**Comment by skftn** [comment]
Using GUI **Monero 'Helium Hydra' (v0.11.1.0-release)**:

- Create wallet
- Password `Á' ` (accented, parenthesis, space)
- Close GUI

Testing in the CLI:

- `./monero-wallet-cli --testnet --wallet-file="/home/dsc/Monero/wallets/accent_test5/accent_test5.keys"`
- password works, wallet opened

Testing in the GUI:
- `./monero-wallet-gui --testnet`
- Enter password `Á' `
- password works, wallet opened

Can't reproduce bug.

**Comment by medusadigital** [comment]
+invalid

**Comment by tikwanleap** [comment]
I just tested again with v0.11.1.0 and it still not working. The password is 50 characters long so skftn's test case may need to be modifed to use a 50 character long password with accents, parenthsis, brackets etc.

**Comment by tikwanleap** [comment]
Ok, here is a test case where I was able to use the password in the cli but not in the gui. This is all using v0.11.1.0 for both.

password:
¥mùh§I¡|

**Comment by danrmiller** [comment]
-invalid

**Comment by xiphon** [comment]
> Ok, here is a test case where I was able to use the password in the CLI but still not working in the GUI. This is all using v0.11.1.0 for both.
> 
> password:
> ¥mùh§I¡|
> 
> Also, I created the wallet in CLI. This is different from skftn's test case where it is created in the GUI.

Can't reproduce this one. @tikwanleap , could you check the latest build?

**Comment by dEBRUYNE-1** [comment]
+resolved
